---
#https://app.swaggerhub.com/apis/deviantony/Portainer/1.19.2/#/users/
- name: Check for portainer admin account
  shell: >
    curl --silent -I -X GET "http://portainer.{{ root_domain }}/api/users/admin/check" -H  "accept: application/json"
  register: admin_account_check
  delegate_to: localhost

- name: Init admin account if it hasn't already
  shell: >
    curl -X POST "http://portainer.{{ root_domain }}/api/users/admin/init" -H  "accept: application/json" -H  \
    "Content-Type: application/json" -d "{  \"Username\": \"admin\",  \"Password\": \"{{ portainer_admin_password }}\"}"
  when: not admin_account_check.stdout | search("204")
  delegate_to: localhost