---
- name: Create appnet
  shell: >
    docker network ls | grep "appnet" ||
    {
      docker network create --driver overlay appnet
    }
  become: true


- name: Place the compose file
  template: 
    src: ../roles/startup-infrastructure/templates/docker-compose.yml.j2 
    dest: /data/startup-infrastructure.yml
    mode: 0600
  become: true

- name: Run stack deploy
  shell: >
    docker stack deploy -c /data/startup-infrastructure.yml startup-infrastructure
  become: true

- name: Give containers time to spin up
  wait_for:
    timeout: 120

- include_tasks: configure-portainer.yml