---

ssh_key_path: {{ rke_ssh_key_location }}

cluster_name: {{ rke_cluster_name }}
ignore_docker_version: true
system_images:
    kubernetes: rancher/hyperkube:v{{ kubernetes_version }}-rancher1

{% if (rook_enabled is defined and rook_enabled | bool == True) or (longhorn_enabled is defined and longhorn_enabled | bool == True) %}
services:
  kubelet:
    extra_args:
      volume-plugin-dir: /usr/libexec/kubernetes/kubelet-plugins/volume/exec
    extra_binds:
      - /usr/libexec/kubernetes/kubelet-plugins/volume/exec:/usr/libexec/kubernetes/kubelet-plugins/volume/exec
{% endif %}

network:
    plugin: canal
    {% if (kubernetes_network_interface is defined) %}

    options:
        canal_iface: {{ kubernetes_network_interface }}
    {% endif %}

nodes:
  {% for node in groups['kube-masters'] %}

  - address: {{node}}
    name: {{node}}
    user: {{standard_user}}
    role:
    - controlplane
    - etcd
  {% endfor %}
  {% for node in groups['kube-workers'] %}

  - address: {{node}}
    name: {{node}}
    user: {{standard_user}}
    role:
    - worker

  {% endfor %}

authentication:
    strategy: x509
    sans:
      - "kubernetes.{{ root_domain }}"