---
# This playbook deploys a development machine
# EXAMPLE:
# ansible-playbook -i ${project_dir}/hosts ${project_dir}/playbooks/site.yml \
# -extra-vars "home_pub_key=<pub-key-location-to-curl> standard_user=<user_name> git_user=<git-user> git_email=<git-email>"

- name: Install ansible dependencies
  hosts: all
  user: root
  gather_facts: no
  serial: 100%
  tasks:
    - include: ../roles/ansible-dependencies/tasks/main.yml

- name: Apply common configuration to all nodes
  hosts: all
  serial: 100%
  roles:
   - role: ../roles/common

- import_playbook: kubernetes.yml

- name: Deploy startup-infrastructure to kubernetes
  hosts: localhost
  connection: local
  roles:
    - role: ../roles/startup-infrastructure
    - role: ../roles/rook-ceph
      when: rook_enabled is defined and rook_enabled | bool == True
    - role: ../roles/longhorn
      when: longhorn_enabled is defined and longhorn_enabled | bool == True
    - role: ../roles/presslabs-mysql